language: python
python:
- 3.6
- 3.5
- 3.4
install:
- pip install -U poetry tox-travis
script: tox
env:
  global:
  - secure: IJm/UzvVcsRpgg9HAzmbBisif9xR2aPlzARlyUFM/qvgKRZ3fbdxDGQV7Yc7Nqd/rXHm5UcJrKN+YwTFaB0qTLrWaJy6c1cdvpGYji7hK0amckJXN1sUUFA/RgRVJ1tt1/J7HmugKScBeG8Pz7icAxDjEYntGWveEWwTyJEZJ/f6cIvRei9lW0OlD/ejR3qMXY+4DHcPfDllmyuXIfjSX3W4JlrSyOofBduK1sj/3KEj7/yZPw6IAUt2WR5tgiEsb1VuJiMRsl6duk3fp55wS2zCMOwi3V6p5Kuz7ItszJ/wdMrN0jGUl0DdyLTraYt8cRGUaGDFNFp9xeic3O2tNEyOi68YdbmZ+LGzfkEGRhX8XMmYjk5zKehDoX4vx28sSWCCXhaJewbLJXmAGtTvawIPYqRAJ/Z4DunEg0ugIj0m8O1sx26HppHazbFkZCD1zmBO+gxm4k6Tt/kWeP6PB3ZUb4X891L+sXNEL1A1HS+TETprqXQveYIfd4GmRM118jCHjArWjwY0T+sTA9g+XPGghYdHWUEZT1VBkNuJBIJ1ZZILisoCVmtnIXV8T6GG8gx17oxQJS8Bhijdlj1WIHAK310XvI4jI9tukKNIV9LTzG/k+E9lirIZtLMCtG4FqA0ppGJoWXDKsPosgWLzQSZi64BYQRJMehppNgQ/tIg=
  - secure: d4vVq9s/m7tKR1dc1H584HzbvIbmydmBN1KRPn8GKgPVvxbD4g1AlQiPebsxrt/RSk5ZibrnA06WmmpXS0KXDMnNr+fg19fW8ssINyc7l9PBQYWAqIku1dfh5zJySOYKqWKxmGGwgnwNd3/E4NETrat/d9cEc3BNJRIkl1HMjU7bLhb/EU28sydwH5je0zR0HJJym9wSBV3XSgjst7zxMbw2iw22RDa3XQ6d0pVQiGn4n1pzlUJ0LHUCwnPImuayS3o8/sIThIqzNozIOzGrN012qCDmWEpnTe4XtMPZg3n6c2ijs9VaV3S3jCP68NvgNYoO7pptCsCn+jvSKyg4MnB0WVoiW64jbn16N2oaersMEc4k9nh1svHgDUxLRY5u0Mk3/i0XgqBwyMJ2x84cmXCzo9Fe6Y4g+7s11kvOeRtY9pgclzLwsnOjPO6ERNG3vhq91nLJKxdFzVcnEuAhhKThymeN7mC2QXZ0JBMnmy/Z95rj8Rn69P1docRb6WBx6swUpxesNygnU9oyZ9DFF7wPByBcjzFtEax7gl16TWOsouRQyr09gn6dx/sh1mzxokinvc24wES9QLt5GpvVpcD6XuikAaed9+gXMSH6ECZlGM/3QCq4AAUUkWkeczxyRhTFkfUXAe5h1p8FbvbTtvltxbtWj4cwH6kWeWzjJk0=

deploy:
  - provider: script
    script: poetry publish --username $PYPI_USER --password $PYPI_PASS --build
    on:
      tags: true
      repo: Metaswitch/announcer
      python: 3.6
