# Copyright (c) Alianza, Inc. All rights reserved.
[tox]
skipsdist = True
envlist = py310, py311, py312, ruff, mypy, coverage

[gh-actions]
python =
    3.10: py310, ruff, mypy, coverage
    3.11: py311
    3.12: py312

[testenv]
allowlist_externals = uv
skip_install = true
commands =
    uv pip install -e .
    uv run --active pytest tests/

[testenv:ruff]
allowlist_externals = uv
skip_install = true
commands =
    uv pip install -e .
    uv run --active ruff check

[testenv:mypy]
allowlist_externals = uv
skip_install = true
commands =
    uv pip install -e .
    uv run --active mypy -p announcer --ignore-missing-imports

[testenv:coverage]
allowlist_externals = uv
skip_install = true
commands =
    uv pip install -e .
    uv run --active pytest --cov=announcer tests
