# Copyright (c) Alianza, Inc. All rights reserved.
name: Announcer
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: bash install.sh
      - run: bash test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
